# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aplnb',
                'doc_host': 'https://answerdotai.github.io',
                'git_url': 'https://github.com/answerdotai/aplnb',
                'lib_path': 'aplnb'},
  'syms': { 'aplnb.core': { 'aplnb.core.APLMagic': ('core.html#aplmagic', 'aplnb/core.py'),
                            'aplnb.core.APLMagic.__init__': ('core.html#aplmagic.__init__', 'aplnb/core.py'),
                            'aplnb.core.APLMagic.apl': ('core.html#aplmagic.apl', 'aplnb/core.py'),
                            'aplnb.core.create_ipython_config': ('core.html#create_ipython_config', 'aplnb/core.py'),
                            'aplnb.core.create_magic': ('core.html#create_magic', 'aplnb/core.py'),
                            'aplnb.core.load_ipython_extension': ('core.html#load_ipython_extension', 'aplnb/core.py')}}}
