"""MiniAPL magics and APL output display for Jupyter and IPython

Docs: https://answerdotai.github.io/aplnb/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto #0
__all__ = ['AplOut', 'APLMagic', 'create_magic', 'load_ipython_extension', 'create_ipython_config']

# %% ../00_core.ipynb #fe6dcafd
import html, json
from importlib.resources import files
from fastcore.utils import *
from miniapl import Session, AplError, symbols
from IPython import get_ipython
from IPython.display import display, Javascript, HTML
from IPython.paths import get_ipython_dir


# %% ../00_core.ipynb #07eae6b5
class AplOut(str):
    "APL output text, displayed in the SAX2 font where HTML is available."
    def __repr__(self): return str(self)
    def _repr_html_(self): return f'<pre class="aplnb_out sax2">{html.escape(self.rstrip(chr(10)))}</pre>'


# %% ../00_core.ipynb #04f56c87
_css = r"""<style>
@font-face { font-family:'SAX2'; src: local('SAX2'), url('https://cdn.jsdelivr.net/gh/abrudz/SAX2@master/SAX2.ttf') format('truetype') }
.sax2 { font-family:'SAX2',monospace !important; line-height:1.05 !important }
</style>"""

class APLMagic:
    "IPython APL magics sharing a lazily started MiniAPL session."
    def __init__(self, session=None): self.session,self._loaded = session,False


# %% ../00_core.ipynb #0b57e64c
@patch
def apl(self:APLMagic, line, cell=None):
    "Evaluate a line as a native value or display a cell as an APL session."
    if self.session is None: self.session = Session()
    if not self._loaded:
        js = files('aplnb')
        keyboard = (files('miniapl')/'keyboard.json').read_text()
        display(Javascript(f"{(js/'lb.js').read_text()}({json.dumps(symbols)}, {(js/'input.js').read_text()}, {keyboard})"))
        display(HTML(_css))
        self._loaded = True
    code = line if cell is None else cell.rstrip()
    show = not (cell is not None and code.endswith(';'))
    if not show: code = code[:-1]
    output = []
    try:
        result = (self.session.eval if cell is None else self.session.run)(code)
        output = result.output
    except (AplError, KeyboardInterrupt) as e:
        output = getattr(e, 'output', [])
        raise
    finally:
        if show and output: display(AplOut('\n'.join(output)))
    if cell is None: return result.value

# %% ../00_core.ipynb #953c6348
def create_magic(shell=None, session=None):
    "Register line and cell magics with `shell`, optionally sharing a MiniAPL `session`."
    if shell is None: shell = get_ipython()
    magic = APLMagic(session)
    shell.register_magic_function(magic.apl, 'line_cell', 'apl')
    return magic


# %% ../00_core.ipynb #3e0cb6bc
def load_ipython_extension(ipython):
    "Register the APL magics when IPython loads this extension."
    create_magic(shell=ipython)

# %% ../00_core.ipynb #66869255
def create_ipython_config():
    "Called by `aplnb_install` to install magic"
    ipython_dir = Path(get_ipython_dir())
    cf = ipython_dir/'profile_default'/'ipython_config.py'
    cf.parent.mkdir(parents=True, exist_ok=True)
    if cf.exists() and 'aplnb' in cf.read_text(): return print('aplnb already installed!')
    with cf.open(mode='a') as f: f.write("\nc.InteractiveShellApp.extensions.append('aplnb')\n\n")
    print(f"Jupyter config updated at {cf}")
