"""Driving Dyalog APL over the RIDE protocol, and `apl` magics for Jupyter and IPython

Docs: https://answerdotai.github.io/aplnb/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto #0
__all__ = ['find_dyalog', 'start_dyalog', 'ride_send', 'ride_recv', 'AplError', 'AplPrompt', 'ride_run', 'Apl', 'AplOut',
           'APLMagic', 'create_magic', 'load_ipython_extension', 'create_ipython_config']

# %% ../00_core.ipynb #fe6dcafd
import atexit,json,socket,subprocess
from shutil import which
from importlib.resources import files
from fastcore.utils import *
from fastcore.test import *
from IPython.display import display, Javascript
from IPython.paths import get_ipython_dir
from IPython.utils.capture import capture_output


# %% ../00_core.ipynb #0c05a3cc
def find_dyalog():
    "Locate the Dyalog interpreter binary"
    if p:=which('mapl') or which('dyalog'): return p
    apps = sorted(Path('/Applications').glob('Dyalog-*.app'))
    if apps: return str(apps[-1]/'Contents/Resources/Dyalog/mapl')
    vers = sorted(Path('/opt/mdyalog').glob('*/*/*/mapl'))
    if vers: return str(vers[-1])
    raise FileNotFoundError('Dyalog APL not found: install it from dyalog.com')

# %% ../00_core.ipynb #ece90862
def start_dyalog(
    dyalog=None,  # Path to the interpreter binary; `find_dyalog()` result if None
    timeout=10,   # Socket timeout (secs), so a client bug can never hang the caller
):
    "Spawn a Dyalog interpreter that connects back to us over RIDE; return `(socket,Popen)`"
    if not dyalog: dyalog = find_dyalog()
    lsn = socket.create_server(('127.0.0.1', 0))
    port = lsn.getsockname()[1]
    env = os.environ | dict(RIDE_INIT=f'CONNECT:127.0.0.1:{port}', RIDE_SPAWNED='1',
        APLCORENAME=os.environ.get('APLCORENAME','0'),
        DYALOGQUIETUCMDBUILD='1', DYALOG_LINEEDITOR_MODE='1', ENABLE_CEF='0', LOG_FILE_INUSE='0')
    dn = subprocess.DEVNULL
    proc = subprocess.Popen([dyalog], env=env, stdin=dn, stdout=dn, stderr=dn)
    lsn.settimeout(10)
    sock,_ = lsn.accept()
    lsn.close()
    sock.settimeout(timeout)
    return sock,proc

# %% ../00_core.ipynb #3ede6ea9
def ride_send(sock, msg):
    "Send one RIDE message: a handshake `str`, or a `[cmd,args]` list sent as JSON"
    if not isinstance(msg,str): msg = json.dumps(msg, separators=(',',':'))
    b = ('RIDE'+msg).encode()
    sock.sendall((len(b)+4).to_bytes(4,'big')+b)

def _recvall(sock, n):
    parts = []
    while n:
        b = sock.recv(n)
        if not b: raise ConnectionError('Dyalog closed the connection')
        parts.append(b)
        n -= len(b)
    return b''.join(parts)

def ride_recv(sock):
    "Receive one RIDE message, JSON-decoded unless it's a handshake string"
    hdr = _recvall(sock, 8)
    assert hdr[4:8]==b'RIDE', f"Bad RIDE header: {hdr}"
    msg = _recvall(sock, int.from_bytes(hdr[:4],'big')-8).decode()
    msg = re.sub(r'[\x00-\x1f]', lambda m: f'\\u{ord(m[0]):04x}', msg)
    return json.loads(msg) if msg[0]=='[' else msg


# %% ../00_core.ipynb #8b0cdcfc
class AplError(Exception): pass

class AplPrompt(Exception):
    "The session stopped at a non-ready prompt: 2=⎕ input, 3=incomplete input, 4=⍞ input"
    def __init__(self, ptype):
        super().__init__(f'prompt type {ptype}')
        self.ptype = ptype

# %% ../00_core.ipynb #538b5ad9
def ride_run(sock, code):
    "Run one or more lines of APL in the session; return `(output,errno)` once the session is ready again"
    lines = [l for l in code.splitlines() if l.strip()]
    ride_send(sock, ['Execute',{'text':'\n'.join(lines)+'\n','trace':0}])
    out,err,pending = '',0,len(lines)
    while True:
        m,a = ride_recv(sock)
        if m=='AppendSessionOutput':
            if a['type']==14: pending -= 1
            elif a['type']!=1: out += a['result']
        elif m=='HadError': err = a['error']
        elif m=='SetPromptType' and a['type']!=0 and not pending:
            if a['type']!=1: raise AplPrompt(a['type'])
            return out,err


# %% ../00_core.ipynb #23638f61
class Apl:
    "A Dyalog APL session over the RIDE protocol"
    def __init__(self, dyalog=None, timeout=10):
        store_attr()
        self._connect()

    def _connect(self):
        self.sock,self.proc = start_dyalog(self.dyalog, self.timeout)
        assert ride_recv(self.sock)=='SupportedProtocols=2'
        ride_send(self.sock, 'SupportedProtocols=2')
        ride_send(self.sock, 'UsingProtocol=2')
        assert ride_recv(self.sock)=='UsingProtocol=2'
        ride_send(self.sock, ['Identify',{'apiVersion':1,'identity':1}])
        self.info = ride_recv(self.sock)[1]
        ride_send(self.sock, ['SetPW',{'pw':32767}])
        atexit.register(self.close)
        while True:
            m,a = ride_recv(self.sock)
            if m=='SetPromptType' and a['type']==1: break


# %% ../00_core.ipynb #32eb4980
@patch
def close(self:Apl):
    "Shut down the interpreter and close the connection"
    atexit.unregister(self.close)
    try: ride_send(self.sock, ['Exit',{'code':0}])
    except OSError: pass
    self.sock.close()
    try: self.proc.wait(3)
    except subprocess.TimeoutExpired:
        self.proc.kill()
        self.proc.wait()

# %% ../00_core.ipynb #cc30073d
@patch
def run(self:Apl, code):
    "Run `code` in the session, returning its output; raises `AplError` on APL errors"
    try: out,err = ride_run(self.sock, code)
    except AplPrompt as e:
        if e.ptype in (2,4):
            ride_run(self.sock, '→' if e.ptype==2 else '')
            raise AplError('Input via ⎕ or ⍞ is not supported in aplnb') from None
        print('Incomplete input wedged the Dyalog interpreter; started a fresh session (workspace lost). See Dyalog/ride#1401')
        self.close()
        self._connect()
        raise AplError('Incomplete input') from None
    if err: raise AplError(out)
    return out

# %% ../00_core.ipynb #07eae6b5
class AplOut(str):
    "Output text from an `Apl` call, displayed verbatim in notebooks"
    def __repr__(self): return str(self)

@patch
def __call__(self:Apl, code):
    "Run `code`, returning session output (or None if there is none)"
    return AplOut(self.run(code)) or None

# %% ../00_core.ipynb #a82d16ca
@patch
def pyval(self:Apl, expr):
    "Evaluate `expr` and return the result as a Python value"
    return json.loads(self.run(f"1(⎕JSON⍠'HighRank' 'Split')({expr})"))

# %% ../00_core.ipynb #4a0c3e58
def _apljson(v):
    "An APL expression that evaluates to the Python value `v`"
    return "⎕JSON'" + json.dumps(v).replace("'", "''") + "'"

@patch
def __getitem__(self:Apl, expr): return self.pyval(expr)

@patch
def __setitem__(self:Apl, nm, v): self.run(f'{nm}←{_apljson(v)}')

# %% ../00_core.ipynb #8a0bb0fe
@patch
def fn(self:Apl, code):
    "A Python callable applying APL function `code` monadically or dyadically"
    def f(*args):
        if len(args)==1: return self.pyval(f'({code}){_apljson(args[0])}')
        a,w = args
        return self.pyval(f'({_apljson(a)})({code}){_apljson(w)}')
    return f

# %% ../00_core.ipynb #9bd19790
@patch
def __enter__(self:Apl): return self

@patch
def __exit__(self:Apl, *args): self.close()

# %% ../00_core.ipynb #04f56c87
class APLMagic:
    def __init__(self, dyalog=None): self.dyalog,self.o,self._loaded = dyalog,None,False

    def apl(self, line, cell=None):
        if not self.o: self.o = Apl(self.dyalog)
        if not self._loaded:
            display(Javascript((files('aplnb')/'lb.js').read_text()))
            self._loaded = True
        if cell is None: return self.o[line.split('⍝')[0].strip()]
        disp,cell = True,cell.rstrip()
        if cell.endswith(';'): disp,cell = False,cell[:-1]
        out = self.o(cell)
        if disp and out: print(out, end='')


# %% ../00_core.ipynb #953c6348
def create_magic(shell=None):
    if not shell: shell = get_ipython()
    apl_magic = APLMagic()
    shell.register_magic_function(apl_magic.apl, 'line_cell', 'apl')
    return apl_magic


# %% ../00_core.ipynb #3e0cb6bc
def load_ipython_extension(ipython):
    "Required function for creating magic"
    create_magic(shell=ipython)

# %% ../00_core.ipynb #66869255
def create_ipython_config():
    "Called by `aplnb_install` to install magic"
    ipython_dir = Path(get_ipython_dir())
    cf = ipython_dir/'profile_default'/'ipython_config.py'
    cf.parent.mkdir(parents=True, exist_ok=True)
    if cf.exists() and 'aplnb' in cf.read_text(): return print('aplnb already installed!')
    with cf.open(mode='a') as f: f.write("\nc.InteractiveShellApp.extensions.append('aplnb')\n\n")
    print(f"Jupyter config updated at {cf}")
