"""Running J in-process through libj, and `j` magics for Jupyter and IPython

Docs: https://answerdotai.github.io/iversonnb/j.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_j.ipynb.

# %% auto #0
__all__ = ['find_j', 'load_j', 'JError', 'J', 'JOut', 'JMagic', 'create_j_magic', 'load_ipython_extension']

# %% ../01_j.ipynb #7e555789
import ctypes
from ctypes import c_void_p,c_char_p,c_int,c_longlong,c_double,c_byte,POINTER,byref,cast,create_string_buffer
from shutil import which
from IPython.display import display
from IPython.utils.capture import capture_output
from fastcore.utils import *
from fastcore.test import *

# %% ../01_j.ipynb #4f9e0882
_LIBJ = 'j.dll' if sys.platform=='win32' else 'libj.dylib' if sys.platform=='darwin' else 'libj.so'

def find_j():
    "Locate the J binary directory: the one containing libj and profile.ijs"
    if (p:=which('jconsole')) and (d:=Path(p).resolve().parent/_LIBJ).exists(): return d.parent
    try:
        import jlang
        return Path(jlang.path())/'bin'
    except ImportError: pass
    roots = [Path.home(), Path('/Applications'), Path('/opt'), Path('/usr/share')]
    cands = sorted(c for r in roots if r.exists() for c in r.glob('j9*') if (c/'bin'/_LIBJ).exists())
    if cands: return cands[-1]/'bin'
    raise FileNotFoundError('J not found: pip install jlanguage, or install it from jsoftware.com')

# %% ../01_j.ipynb #ee362390
_OUTCB = ctypes.CFUNCTYPE(None, c_void_p, c_int, c_void_p)   # Joutput(jt, type, text)
_INCB  = ctypes.CFUNCTYPE(c_void_p, c_void_p, c_char_p)      # Jinput(jt, prompt) -> line
_SMCON = 3   # smoptions: identify as a console front end

def load_j(jbin=None):
    "Load libj from `jbin` (or `find_j()`), declare its C signatures, and return `(jbin,lib)`"
    jbin = Path(jbin or find_j())
    lib = ctypes.CDLL(str(jbin/_LIBJ))
    lib.JInit2.restype = c_void_p
    lib.JInit2.argtypes = [c_char_p]
    lib.JDo.argtypes = [c_void_p,c_char_p]
    lib.JSM.argtypes = [c_void_p,c_void_p]
    lib.JInterrupt.argtypes = lib.JFree.argtypes = [c_void_p]
    lib.JGetM.argtypes = lib.JSetM.argtypes = [c_void_p,c_char_p]+[POINTER(c_longlong)]*4
    return jbin,lib

# %% ../01_j.ipynb #e8a80100
class JError(Exception):
    "A J error, carrying the session's output (including the error display) as its message"

# %% ../01_j.ipynb #30e60cf7
class J:
    "A J session: the libj engine loaded in-process, with the stdlib profile booted"
    def __init__(self, jbin=None):
        self.jbin,self._lib = load_j(jbin)
        self.jt = self._lib.JInit2(str(self.jbin).encode())
        self._out,self._inq,self.exited = [],[],None
        @_OUTCB
        def _o(j,typ,p):
            if typ==5: self.exited = p or 0
            else: self._out.append((typ, ctypes.string_at(p).decode('utf-8','replace') if p else ''))
        @_INCB
        def _i(j,prompt):
            self._inbuf = create_string_buffer((self._inq.pop(0) if self._inq else ')').encode())
            return ctypes.addressof(self._inbuf)
        self._cbs = (c_void_p*5)(cast(_o,c_void_p), None, cast(_i,c_void_p), None, _SMCON)
        self._lib.JSM(self.jt, self._cbs)
        boot = f"(3 : '0!:0 y')<BINPATH,'/profile.ijs'[ARGV_z_=:<'jconsole'[BINPATH_z_=:'{self.jbin}'"
        if self._lib.JDo(self.jt, boot.encode()): raise JError(''.join(t for _,t in self._out))

# %% ../01_j.ipynb #db9dc5bf
@patch
def run(self:J, code):
    "Run `code` (one or more lines of J) in the session, returning its output; raises `JError` on J errors"
    self._out.clear()
    self._inq[:] = code.strip().splitlines()
    while self._inq and self.exited is None:
        rc = self._lib.JDo(self.jt, self._inq.pop(0).encode())
        if rc and self.exited is None: raise JError(''.join(t for _,t in self._out))
    if self.exited is not None: return ''.join(t for ty,t in self._out if ty!=2)   # drop the exit unwind noise
    return ''.join(t for _,t in self._out)

# %% ../01_j.ipynb #8d7be472
class JOut(str):
    "Output text from a `J` call; displays verbatim"
    def __repr__(self): return str(self)

@patch
def __call__(self:J, code):
    "Run `code`, returning session output (or None if there is none)"
    return JOut(self.run(code)) or None

# %% ../01_j.ipynb #b4ba14ce
def _nest(x, shape):
    "Nest flat sequence `x` (row-major ravel) into `shape`"
    if len(shape)<2: return x
    n = len(x)//shape[0]
    return [_nest(x[i*n:(i+1)*n], shape[1:]) for i in range(shape[0])]

@patch
def getm(self:J, name):
    "Read noun `name` into Python: str for characters; int/float scalars and (nested) lists otherwise"
    t,r,s,d = c_longlong(),c_longlong(),c_longlong(),c_longlong()
    if self._lib.JGetM(self.jt, name.encode(), byref(t),byref(r),byref(s),byref(d)): raise JError(f'no noun: {name}')
    shape = cast(s.value, POINTER(c_longlong))[:r.value]
    n = math.prod(shape)
    if t.value==2: return _nest(ctypes.string_at(d.value, n).decode('utf-8','replace'), shape)
    if t.value not in (1,4,8): raise JError(f'unsupported J type {t.value} for: {name}')
    x = cast(d.value, POINTER({1:c_byte,4:c_longlong,8:c_double}[t.value]))[:n]
    return _nest(x, shape) if r.value else x[0]

# %% ../01_j.ipynb #86f8fb28
@patch
def pyval(self:J, expr):
    "Evaluate `expr` and return the result as a Python value"
    self.run(f'jnbtmp =: {expr}')
    try: return self.getm('jnbtmp')
    finally: self.run("4!:55 <'jnbtmp'")

@patch
def __getitem__(self:J, expr): return self.pyval(expr)

# %% ../01_j.ipynb #89f0e80f
def _flat(o): return [a for x in o for a in _flat(x)] if isinstance(o,(list,tuple)) else [o]

def _jdat(v):
    "ctypes `(type,shape,buf)` for a Python scalar, string, or uniformly nested list"
    if isinstance(v,str):
        b = v.encode()
        return 2, [len(b)], create_string_buffer(b, len(b))
    shape,x = [],v
    while isinstance(x,(list,tuple)): shape,x = shape+[len(x)],x[0]
    flat = _flat(v)
    if any(isinstance(a,float) for a in flat): return 8, shape, (c_double*len(flat))(*flat)
    return 4, shape, (c_longlong*len(flat))(*flat)

@patch
def __setitem__(self:J, nm, v):
    "Assign Python value `v` (scalar, string, or nested list) to noun `nm`"
    t,shape,buf = _jdat(v)
    sh = (c_longlong*len(shape))(*shape)
    a = [c_longlong(t), c_longlong(len(shape)), c_longlong(ctypes.addressof(sh)), c_longlong(ctypes.addressof(buf))]
    if self._lib.JSetM(self.jt, nm.encode(), *map(byref,a)): raise JError(f'JSetM failed: {nm}')

# %% ../01_j.ipynb #b3270978
@patch
def fn(self:J, code):
    "A Python callable applying J verb `code` monadically or dyadically (left argument first)"
    def f(*args):
        if len(args)==1:
            self['jnby'] = args[0]
            return self.pyval(f'({code}) jnby')
        self['jnbx'],self['jnby'] = args
        return self.pyval(f'jnbx ({code}) jnby')
    return f

# %% ../01_j.ipynb #79911134
@patch
def interrupt(self:J):
    "Stop the currently running sentence with an attention interrupt; safe to call from another thread"
    self._lib.JInterrupt(self.jt)

# %% ../01_j.ipynb #af540693
@patch
def close(self:J):
    "Free the engine instance; the session is unusable afterwards"
    self._lib.JFree(self.jt)
    self.jt = None

@patch
def __enter__(self:J): return self

@patch
def __exit__(self:J, *args): self.close()

# %% ../01_j.ipynb #12c1ebee
class JMagic:
    "IPython `%j`/`%%j` magics, driving a lazily-started `J` session"
    def __init__(self, jbin=None): self.jbin,self.o = jbin,None

    def j(self, line, cell=None):
        "Run J: a cell magic displays the session output; a line magic returns the expression's Python value"
        if not self.o: self.o = J(self.jbin)
        if cell is None: return self.o[line.strip()]
        disp,cell = True,cell.rstrip()
        if cell.endswith(';'): disp,cell = False,cell[:-1]
        out = self.o(cell)
        if disp and out: display(out)

# %% ../01_j.ipynb #00b65478
def create_j_magic(shell=None):
    "Create a `JMagic` and register its `j` line/cell magic with `shell`, returning it"
    if not shell: shell = get_ipython()
    jm = JMagic()
    shell.register_magic_function(jm.j, 'line_cell', 'j')
    return jm

def load_ipython_extension(ipython):
    "Required function for creating magic"
    create_j_magic(shell=ipython)
